retrofit:
  connectTimeout: 60000
  readTimeout: 60000
  callTimeout: 60000
  writeTimeout: 60000
  retryOnConnectionFailure: true
services:
  opsmx:
    baseUrl: http://localhost:8085
    enabled: true
  autopilot:
    baseUrl: http://localhost:8090
    enabled: true
  platform:
    baseUrl: http://localhost:8095
    enabled: true
    userGroupApiPath: /platformservice/v1/users/{username}/usergroups/importAndCache
  dashboard:
    baseUrl: http://localhost:8094
    enabled: true
  visibility:
    baseUrl: http://localhost:8096
    enabled: true
  auditservice:
    baseUrl: http://localhost:8097
    enabled: true
  auditclient:
    baseUrl: http://localhost:8098
    enabled: true
  oesui:
    externalUrl: https://qateam-saml.isd-dev.opsmx.net/ui
  keel:
    enabled: false
  clouddriver:
    baseUrl: http://localhost:7002
    enabled: true
    host: 0.0.0.0
    port: 7002
  clouddriverCaching:
    baseUrl: http://localhost:7002
    enabled: true
    host: 0.0.0.0
    port: 7002
  clouddriverRo:
    baseUrl: http://localhost:6001
    enabled: true
    host: 0.0.0.0
    port: 7002
  clouddriverRoDeck:
    baseUrl: http://localhost:6002
    enabled: true
    host: 0.0.0.0
    port: 7002
  clouddriverRw:
    baseUrl: http://localhost:6003
    enabled: true
    host: 0.0.0.0
    port: 7002
  deck:
    baseUrl: https://qateam-saml.isd-dev.opsmx.net/deck
    enabled: true
    host: 0.0.0.0
    port: 9000
  echo:
    baseUrl: http://localhost:8089
    enabled: true
    host: 0.0.0.0
    port: 8089
  echoScheduler:
    baseUrl: http://localhost:8089
    enabled: true
    host: 0.0.0.0
    port: 8089
  echoWorker:
    baseUrl: http://localhost:6004
    enabled: true
    host: 0.0.0.0
    port: 8089
  fiat:
    baseUrl: http://localhost:7003
    enabled: true
    host: 0.0.0.0
    port: 7003
  front50:
    baseUrl: http://localhost:8080
    enabled: true
    host: 0.0.0.0
    port: 8080
  gate:
    baseUrl: https://qateam-saml.isd-dev.opsmx.net/gate
    enabled: true
    host: 0.0.0.0
    port: 8084
  igor:
    baseUrl: http://localhost:8088
    enabled: true
    host: 0.0.0.0
    port: 8088
  kayenta:
    baseUrl: http://localhost:8090
    enabled: false
    host: 0.0.0.0
    port: 8090
  orca:
    baseUrl: http://localhost:8083
    enabled: true
    host: 0.0.0.0
    port: 8083
  redis:
    baseUrl: redis://:password@localhost:6379
    enabled: true
    host: 0.0.0.0
    port: 6379
  rosco:
    baseUrl: http://localhost:8087
    enabled: true
    host: 0.0.0.0
    port: 8087
  user: {}
cors:
  allowed-origins-pattern: "^https?://(?:localhost|qateam-saml.isd-dev.opsmx.net|/deck/|opsmx.com)(?::[1-9]\\d*)?/?"
ldap:
  enabled: true
  groupRoleAttributes: cn
  groupSearchBase: "ou=groups,dc=opsmx,dc=com"
  groupSearchFilter: "member={0}"
  managerDn: "cn=manager,dc=opsmx,dc=com"
  managerPassword: manager123
  url: "ldap://nonprd-ldap.opsmx.com"
  userDnPattern: "uid={0},ou=users,dc=opsmx,dc=com"
security:
  basic:
    enabled: true
  user: {}
file:
  enabled: false
  url: /platformservice/v1/users/authenticate
authn:
  mode: session
google: {}
redis:
  connection: "redis://:password@localhost:6379"
server:
  port: 8084
  session:
    timeoutInSeconds: 7200
  tomcat:
    httpsServerPort: X-Forwarded-Port
    internalProxies: .*
    protocolHeader: X-Forwarded-Proto
    remoteIpHeader: X-Forwarded-For
management:
  health:
    elasticsearch:
      enabled: false
    ldap:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
gate:
  installation:
    mode: common #Allowed values are --> oes,common
rbac:
  feature:
    application:
      enabled: true
spinnaker:
  extensibility:
    plugins:
    deck-proxy:
      enabled: true
      plugins:
        Opsmx.VerificationGatePlugin:
          enabled: true
          version: 1.0.1
        Opsmx.TestVerificationGatePlugin:
          enabled: true
          version: 1.0.1
        Opsmx.PolicyGatePlugin:
          enabled: true
          version: 1.0.1
        Opsmx.VisibilityApprovalPlugin:
          enabled: true
          version: 1.0.1
    repositories:
      opsmx-repo:
        url: file:///opt/spinnaker/plugins/plugins.json
        #url: https://raw.githubusercontent.com/OpsMx/spinnakerPluginRepository/v3.10.0/plugins.json
#If the flag is false, the corresponding endpoints will move to protected mode and redirect the user to the login page.
#Otherwise, it will allow unauthenticated access to the endpoints. Default will be false.
allowUnauthenticatedAccess:
  agentAPI: false
  webhooks: true
logging:
  level:
    com.netflix.spinnaker.gate.security: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
spring:
  cloud:
    vault:
      enabled: false
